export enum HiveWorkerType {
    Cache = "cache",
    Config = "config",
    Date = "date",
    Database = "database",
    DataLifecycleFunction = "dataLifecycleFunction",
    Encryption = "encryption",
    Error = "error",
    Feature = "feature",
    FileSystem = "fileSystem",
    GraphBuilder = "graphBuilder",
    GraphEndpointFunction = "graphEndpointFunction",
    Log = "log",
    PubSubServer = "pubSubServer",
    PubSubClient = "pubSubClient",
    RestEndpointFunction = "restEndpointFunction",
    Server = "server",
    Storage = "storage",
    TaskFunction = "taskFunction",
    Token = "token",
    User = "user",
    Unknown = "unknown",
}
