env:
    browser: true
    amd: true
    node: true
root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
    - "prettier/@typescript-eslint"
    - "plugin:prettier/recommended"
    - "plugin:import/recommended"
    - "plugin:import/electron"
    - "plugin:import/typescript"
    - "plugin:react-hooks/recommended"
rules:
    "@typescript-eslint/ban-types": off
    "@typescript-eslint/explicit-module-boundary-types": off
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-inferrable-types": off
    "@typescript-eslint/no-unused-vars": off
    "@typescript-eslint/triple-slash-reference": off
    "no-case-declarations": off
overrides:
    - files:
          - "*.js"
      rules:
          - "@typescript-eslint/no-var-requires": off
