export enum VsCodeCommand {
    AddServer = "ohServers.addServer",
    EditServer = "ohServers.editServer",
    EditServerEnvironment = "ohServers.editServerEnvironment",
    EditServerWorkers = "ohServers.editServerWorkers",
    GraphBrowser = "ohServers.graphBrowser",
    LogViewer = "ohServers.logViewer",
    Reconnect = "ohServers.reconnect",
    RefreshSchema = "ohServers.refreshSchema",
    RemoveAllServers = "ohServers.removeAllServers",
    RemoveServer = "ohServers.removeServer",
    RawEditor = "ohServers.rawEditor",
    RetrieveToken = "ohServers.retrieveToken",
    SwaggerBrowser = "ohServers.swaggerBrowser",
}
