export enum HiveWorkerType {
    Cache = "cache",
    Date = "date",
    Database = "database",
    DataLifecycleFunction = "dataLifecycleFunction",
    Encryption = "encryption",
    Error = "error",
    FeatureFlag = "featureFlag",
    FileSystem = "fileSystem",
    GraphBuilder = "graphBuilder",
    GraphEndpointFunction = "graphEndpointFunction",
    HiveAccount = "hiveAccount",
    Log = "log",
    PubSubServer = "pubSubServer",
    PubSubClient = "pubSubClient",
    RestEndpointFunction = "restEndpointFunction",
    Storage = "storage",
    TaskFunction = "taskFunction",
    Token = "token",
    User = "user",
    Unknown = "unknown",
    WorkflowFunction = "workflowFunction",
}
