export enum AdminEventType {
    AccessTokenRequest = "access-token-request",
    AccessTokenResponse = "access-token-response",
    ConfigRequest = "config-request",
    ConfigResponse = "config-response",
    ConfigSaveRequest = "config-save-request",
    ConfigSaveResponse = "config-save-response",
    Connection = "connection",
    Disconnect = "disconnect",
    LogResponse = "log-response",
    RegisterRequest = "register-request",
    RegisterResponse = "register-response",
    ServerResetRequest = "server-reset-request",
    ServerResetResponse = "server-reset-response",
    StartLogRequest = "start-log-request",
    StartLogResponse = "start-log-response",
    StatusRequest = "status-request",
    StatusResponse = "status-response",
    StopLogRequest = "stop-log-request",
    StopLogResponse = "stop-log-response",
    UnknownRequest = "unknown-request",
    UnknownResponse = "unknown-response",
    UrlListRequest = "url-list-request",
    UrlListResponse = "url-list-response",
}
