module.exports = {
    docs: [
        {
            type: "category",
            label: "Foreword",
            collapsed: true,
            items: ["foreword/why-we-built-omnihive", "foreword/what-plug-and-play-means"],
        },
        {
            type: "category",
            label: "Getting Started",
            collapsed: false,
            items: [
                "getting-started/installation",
                "getting-started/setup-local-instance",
                "getting-started/custom-worker-development",
                "getting-started/vscode-extension",
            ],
        },
        {
            type: "category",
            label: "A deeper look",
            collapsed: true,
            items: ["deeper-look/configuration-file", "deeper-look/graph-builder"],
        },
        {
            type: "category",
            label: "Core Helpers",
            collapsed: true,
            items: ["helpers/async-helper", "helpers/object-helper", "helpers/string-builder", "helpers/string-helper"],
        },
        {
            type: "category",
            label: "Provided Workers",
            collapsed: true,
            items: ["workers/database-worker"],
        },
        {
            type: "category",
            label: "Provided Interfaces",
            collapsed: true,
            items: [
                "interfaces/cache-worker",
                "interfaces/config-worker",
                "interfaces/database-worker",
                "interfaces/date-worker",
                "interfaces/encryption-worker",
                "interfaces/error-worker",
                "interfaces/feature-worker",
                "interfaces/file-system-worker",
                "interfaces/graph-builder-worker",
                "interfaces/graph-endpoint-worker",
                "interfaces/hive-worker",
                "interfaces/log-worker",
                "interfaces/pub-sub-client-worker",
                "interfaces/pub-sub-server-worker",
                "interfaces/rest-endpoint-worker",
                "interfaces/server-worker",
                "interfaces/storage-worker",
                "interfaces/task-endpoint-worker",
                "interfaces/token-worker",
                "interfaces/user-worker",
            ],
        },
        {
            type: "category",
            label: "Provided Enumerations",
            collapsed: true,
            items: [
                "enums/admin-event-type",
                "enums/admin-room-type",
                "enums/hive-worker-type",
                "enums/lifecycle-worker-action",
                "enums/lifecycle-worker-stage",
                "enums/local-function-type",
                "enums/omnihive-log-level",
                "enums/query-cache-type",
                "enums/registered-url-type",
                "enums/rest-method",
                "enums/server-status",
            ],
        },
        {
            type: "category",
            label: "Provided Models",
            collapsed: true,
            items: [
                "models/admin-request",
                "models/admin-response",
                "models/auth-user",
                "models/client-settings",
                "models/connection-schema",
                "models/converter-sql-info",
                "models/graph-context",
                "models/graphql-json",
                "models/hive-worker",
                "models/hive-worker-base",
                "models/hive-worker-metadata-config-database",
                "models/hive-worker-metadata-database",
                "models/hive-worker-metadata-graph-builder",
                "models/hive-worker-metadata-lifecycle-function",
                "models/hive-worker-metadata-rest-function",
                "models/hive-worker-metadata-server",
                "models/proc-function-schema",
                "models/pub-sub-listener",
                "models/registered-hive-worker",
                "models/registered-url",
                "models/rest-endpoint-execute-response",
                "models/server-settings",
                "models/table-schema",
                "models/worker-getter-base",
                "models/worker-setter-base",
            ],
        },
    ],
};
